- hosts: all
  become: yes
  tasks:
  - name: Install packages
    ansible.builtin.apt:
      name: 
        - apache2
        - tree
        - unzip
      state: present
      update_cache: yes


- hosts: all
  become: yes
  tasks:
    - name: Start apache service, if not started
      ansible.builtin.system:
        name: apache2
        state: started
        enabled: true


- name: Execute the command in remote shell; stdout goes to the specified file on the remote shell
  ansible.builtin.shell: sudo useradd tim 

 